### ISSUE TITLE
LTL parser unintelligible

### ISSUE THREAD

**Issue by alaarman** [utwente-fmt/ltsmin#105]
Something as simple as checking a proposition to be true is not easy with the changes to the expression parser. In the below example all state slots are of type bool (see --labels output below). I understand bools are now first-class citizens in the language. Yet, when I check 'slot==true', an error is raised. When I change to 'slot="true"' (quoted "true") the parser goes through, but I have no idea whether this has the expected semantics (e.g. "true" is not in the --labels output).

$ pins2lts-mc/etf2lts-mc ./gal.etf --pins-guards --when --ltl 'X((((LTLAP1==true))U((LTLAP1==true)))U((LTLAP4==true)))' 
etf2lts-mc, 0.000: ETF language module initialized
etf2lts-mc( 0/ 4), 0.003: Loading model from ./gal.etf
etf2lts-mc( 2/ 4), 0.012: LTL layer: formula: X((((LTLAP1==true))U((LTLAP1==true)))U((LTLAP4==true)))
etf2lts-mc( 2/ 4), 0.012, ** error **: Incompatible type formats (LHS = "enum", RHS = "Boolean") for expression: "(LTLAP1 ==  true )", expecting format pair (LHS, RHS) to be any pair in {(direct, direct), (direct, [.,.]), (direct, Signed 32-bit integer), ([.,.], direct), ([.,.], [.,.]), ([.,.], Signed 32-bit integer), (chunk, chunk), (chunk, enum), (enum, chunk), (enum, enum), (Boolean, Boolean), (Boolean, trilean), (trilean, Boolean), (trilean, trilean), (Signed 32-bit integer, direct), (Signed 32-bit integer, [.,.]), (Signed 32-bit integer, Signed 32-bit integer)}

)$ pins2lts-mc/etf2lts-mc ./gal.etf  --labels
etf2lts-mc: ETF language module initialized
etf2lts-mc( 0/ 4): Loading model from ./gal.etf
The state labels are:
   0: enabled0:bool
   1: enabled1:bool
   2: enabled2:bool
   3: enabled3:bool
   4: enabled4:bool
   5: enabled5:bool
   6: enabled6:bool
   7: enabled7:bool
   8: enabled8:bool
   9: enabled9:bool
  10: enabled10:bool
  11: enabled11:bool
  12: LTLAP0:bool
  13: LTLAP1:bool
  14: LTLAP2:bool
  15: LTLAP3:bool
  16: LTLAP4:bool
  17: LTLAP5:bool
  18: LTLAP6:bool
  19: LTLAP7:bool
  20: LTLAP8:bool
  21: LTLAP9:bool
  22: LTLAP10:bool
  23: LTLAP11:bool
The edge labels are:
   0: action:action
The registered types are:
   0: int (enum)
   1: action (enum)
   2: bool (enum)
The state vector is:
   0: Section_4:int
   1: F7:int
   2: Section_2:int
   3: Section_9:int
   4: Section_11:int
   5: F2:int
   6: Section_6:int
   7: F9:int
   8: F3:int
   9: Section_12:int
  10: F12:int
  11: F6:int
  12: F1:int
  13: Section_3:int
  14: Section_10:int
  15: F8:int
  16: F10:int
  17: Section_5:int
  18: Section_8:int
  19: Section_7:int
  20: F5:int
  21: F11:int
  22: F4:int
  23: Section_1:int
The registered types values are:
   0: "tr0" (action)
   1: "tr1" (action)
   2: "tr2" (action)
   3: "tr3" (action)
   4: "tr4" (action)
   5: "tr5" (action)
   6: "tr6" (action)
   7: "tr7" (action)
   8: "tr8" (action)
   9: "tr9" (action)
  10: "tr10" (action)
  11: "tr11" (action)

**Comment by alaarman** [comment]
The error message is still unintelligible for a user.

**Comment by alaarman** [comment]
[gal.etf.zip](https://github.com/utwente-fmt/ltsmin/files/982954/gal.etf.zip)

**Comment by Meijuh** [comment]
To continue working with the ETF (and to use atomic predicates) you can simply add the "false", and "true" strings to the ETF, i.e., change:

    begin sort bool
    end sort

to

    begin sort bool
    "false"
    "true"
    end sort

Meaning you have to use `"false"`, and `"true"` in the atomic predicates. You can do this for the integers too, but then you need to find out which values are reachable.

**Comment by alaarman** [comment]
If this is only for ETF, then it can have less priority and perhaps should be a different issue.

The error message should however be improved because the user has no clue about chunks, enums, etc.

**Comment by alaarman** [comment]
Ideally, we refer to a manual page that explains the built in types and the --labels output.

**Comment by Meijuh** [comment]
Fixed.
