### ISSUE TITLE
POR: support LTL+X formulae

### ISSUE THREAD

**Issue by alaarman** [utwente-fmt/ltsmin#106]
Currently LTL+X formulae are accepted, but the reduction is incorrect.

We can decompose the Buchi in SCCs marking SCCs containing a next-operator or leading to an SCC with next-operator with a new dedicated state label (to be defined in ltsmin-standard.h).
The POR reduction should be turned off for states in the global state space where the next-label is true.

Pins2pins-ltl.c already contains an SCC decomposition of the Buchi automaton (see is_weak).

https://spot.lrde.epita.fr/ltlfilt.html
https://spot.lrde.epita.fr/trans.html#f=!((X((((%22Section_9%3E%3D1%22)%26%26(%22F10%3E%3D1%22))U((%22Section_9%3E%3D1%22)%26%26(%22F10%3E%3D1%22)))U((%22Section_6%3E%3D1%22)%26%26(%22F7%3E%3D1%22)))))&r=br&r=lf&r=si&r=eu&o=a&ff=o&mf=n&af=t&ra=t&rf=d&tf=a&t=fm&fm=od&fm=sm&ta=lc&lo=T&l3=l&l3=A&l3=P&l3=o&l3=p&l3=C&l3=M&cs=s&as=ps&ec=Cou99&eo=&to=s&to=m

**Comment by Meijuh** [comment]
I guess we can do a parse of tree representing the LTL formula right? Just check if there is a `X` in there, and if POR is enabled abort.

**Comment by alaarman** [comment]
indeed

**Comment by Meijuh** [comment]
fixed
