### ISSUE TITLE
pins2lts-sym.c is now only compiled once, meaning that compile flags dont have any effect.

### ISSUE THREAD

**Issue by Meijuh** [utwente-fmt/ltsmin#112]
Such as flags defined in pins-impl.h.

**Comment by alaarman** [comment]
#111 is affected as well.

**Comment by alaarman** [comment]
Tom has a patch on his branch (a partial revert of the compile-once commit).

**Comment by Meijuh** [comment]
Okay, I'll close this issue when Tom's commits are merged.

**Comment by trolando** [comment]
I'll do a pull request of some of the commits

**Comment by alaarman** [comment]
#114 also fixes it and leaves the one-time compilation intact

**Comment by Meijuh** [comment]
I think the best solution for now is to do a pull request of @trolando's next branch. And postpone the refactoring of the symtool to v3.1.0.

**Comment by Meijuh** [comment]
I ended up cherry-picking a necessary commit from @trolando next branch: 93b5abb5f1b2350e87fcecce48a27021d9181eca.
This issue is solved now.
