### ISSUE TITLE
Bad order in LDD64

### ISSUE THREAD

**Issue by alaarman** [utwente-fmt/ltsmin#117]
(also for elevator.3.dve and other models)

$ pins2lts-sym/dve2lts-sym adding.4.dve2C --vset=ldd64
Lace warning: hwloc_set_cpubind returned -1!
Lace error: Unable to bind worker memory to node!
Lace warning: hwloc_get_area_membind_nodeset returned -1!
Lace warning: Lace worker memory not bound with BIND policy!
dve2lts-sym: Exploration order is bfs-prev
dve2lts-sym: Saturation strategy is none
dve2lts-sym: Guided search strategy is unguided
dve2lts-sym: Attractor strategy is default
dve2lts-sym: Precompiled divine module initialized
dve2lts-sym: opening adding.4.dve2C
dve2lts-sym: state vector length is 5; there are 6 groups
dve2lts-sym: Creating a native ListDD 64-bit domain.
dve2lts-sym: initial node table has 832040 entries
dve2lts-sym: initial uniq table has 1346269 entries
dve2lts-sym: initial op cache has 1346269 entries
dve2lts-sym: initial stack size 17711
dve2lts-sym: Using GBgetTransitionsShortR2W as next-state function
dve2lts-sym: got initial state
....
dve2lts-sym: level 29 is finished
dve2lts-sym, ** error **: bad order 37 (2) 31 (2)

**Comment by alaarman** [comment]
[badorder.zip](https://github.com/utwente-fmt/ltsmin/files/1047658/badorder.zip)

**Comment by Meijuh** [comment]
This is fixed with 88541fa4e4e72485f353d850ded593880e159077.
