### ISSUE TITLE
Always Return 0, but state if a counter-example was found or not for LTL

### ISSUE THREAD

**Issue by yanntm** [utwente-fmt/ltsmin#118]
Currently, the return value 1 is supposed to be used to determine if a violation was found or not.

This behavior leads to a lot of problems for me, because the tool DID NOT FAIL, but returns non zero, so this is not a standard behavior for a Unix command. 

Please 
1. Add a message that states "violation not found", to complement the existing "violation found"
2. Drop the non zero return value when no runtime error happens.

I get this sort of stuff :
Jun 13, 2017 11:43:24 PM fr.lip6.move.gal.itstools.Runner runTool
INFO: Standard error output from running tool CommandLine [args=[/home/travis/build/yanntm/ITS-Tools-pnmcc/lts_install_dir/bin/pins2lts-seq, ./gal.so, --when, --ltl, ([]([]((LTLAP1==true))))U(X([]((LTLAP2==true))))], workingDir=/home/travis/build/yanntm/ITS-Tools-pnmcc/INPUTS/SafeBus-COL-03]
/home/travis/build/yanntm/ITS-Tools-pnmcc/lts_install_dir/bin/pins2lts-seq: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.17' not found (required by /home/travis/build/yanntm/ITS-Tools-pnmcc/lts_install_dir/bin/pins2lts-seq)
Exit code :1
FORMULA SafeBus-COL-03-LTLCardinality-1 TRUE TECHNIQUES PARTIAL_ORDER EXPLICIT LTSMIN SAT_SMT

So yes, it's my fault the GLIBC version was wrong, but as you can see my verdict thing is in sore trouble to deduce what actually happened, it did see return value 1 but did not crash on it, because it's "supposed" to be "normal" for ltsmin to give non zero values back. 

You cannot as developer of a tool control all the error codes I believe this is a good example of it.
The Unix  standard is to return 0 unless "something bad" happened. 
Finding counter-examples is not "something bad".

**Comment by alaarman** [comment]
This is by design. A wrapper script can solve the issue.
In principle, we assume the return value 1 is reserved.

I am not against the "violation not found" output.

**Comment by yanntm** [comment]
Ok, 
I'll take the 'violation not found', that solves my tool chain issue.

I guess this non zero return value is used in other toolchains.

It might be by design, but it does not respect standards, which are important too imho.
Here I'm getting return code 1 from running the tool, not by design (by Unix standard !), but I don't see how you could catch this from the code.

A wrapper looking at the output could return 1 pretty easily (iff. return code 0 and analysis of output ...) so the argument holds both ways. 
But a contrario, I can't wrap correctly if the tool returns 1 not by design, such as this case, and only testing absence of "violation found" in output is weak in case the tool fails.

Anyway, let's go for "violation not found".

**Comment by yanntm** [comment]
Also other tools in the suite don't behave homogeneously, e.g. -d does not report 1 if it found deadlocks.
At least with -seq that I was using.
So I don't know why the LTL case is different.

**Comment by Meijuh** [comment]
I fixed for the case of the sequential backend.
Now it still has to be reported for LTL properties.

**Comment by Meijuh** [comment]
@alaarman can you fix this for LTL properties?

**Comment by Meijuh** [comment]
LTSmin now outputs that the formula holds.
