### ISSUE TITLE
Cannot disable Opaal build

### ISSUE THREAD

**Issue by yanntm** [utwente-fmt/ltsmin#123]
There is no configure option that can bypass construction of Opaal targets.
Passing one of 
--disable-opaal
or
--without-opaal 

to configure should work.

**Comment by alaarman** [comment]
Dear Yann,

Is there a reason to have this? Iirc the opaal frontend does not link to any libraries.


Alfons

**Comment by yanntm** [comment]
Well configure displays a check for it (that can never be false currently), and it's just a couple of lines for the setting in configure.ac to fix it like the other flags.
My build tries to only make pins2lts-seq and pins2lts-mc + the headers, but I have to manually cull unneeded targets.
But no, it is not a big issue by any means.

**Comment by alaarman** [comment]
Ah I see. No, good to have it reported.

**Comment by yanntm** [comment]
Similarly, there is no way to disable the pnml front-end build

**Comment by Meijuh** [comment]
fixed
