### ISSUE TITLE
Apply strip -s to all binaries produces in a travis release build.

### ISSUE THREAD

**Issue by Meijuh** [utwente-fmt/ltsmin#124]

**Comment by trolando** [comment]
Motivation?

A reason to keep them is that bug reports include more information, e.g., source code lines.

**Comment by Meijuh** [comment]
The motivation is that an extracted LTSmin release now is ~1GB, which is quite big. The binaries are ~15% of the original size if we apply strip -s. I am going to change the .travis.yml. If we then run into major issues, we can change it back.

**Comment by Meijuh** [comment]
fixed
