### ISSUE TITLE
pnml2lts-mc on more than 64 cores crashes with error

### ISSUE THREAD

**Issue by jacopol** [utwente-fmt/ltsmin#132]
On caserta:
pnml2lts-mc problem101.pnml
pnml2lts-mc( 4/192), ** error **: No more than 64 threads are supported.

LTSmin (HRE?) should have the following behaviour:
If the user specifies --threads=128 => fail with error (like above)
default: should be --threads=min(64,available cores)

(similar with pnml2lts-sym --lace-workers, but I understood that Sylvan 1.1.4 solved that already)

**Comment by Meijuh** [comment]
@alaarman small fix right?

**Comment by alaarman** [comment]
yep

**Comment by alaarman** [comment]
Fixed in 3897e689e04653172c36b1e0b616249cc93e68df
