### ISSUE TITLE
pnml2lts-mc -h could crash in a pipe

### ISSUE THREAD

**Issue by jacopol** [utwente-fmt/ltsmin#133]
pnml2lts-mc -h --threads=1 | cat
*** segmentation fault ***

(without the pipe it works correctly, although I have also seen it failing)

**Comment by jacopol** [comment]
gdb -- pnml2lts-mc -h 2>&1 | cat
(gdb) r
pnml2lts-mc, ** error **: not enough arguments

I don't get why this message is now generated.

**Comment by Meijuh** [comment]
I've looked into this a bit. And the segfault also seems the happen when you window is too small, eg in tmux. The issue seems to be this line: `{"strategy", 0, POPT_ARG_STRING,
     &arg_strategy, 0, "select the search strategy (default: auto)",
     "<bfs|sbfs|dfs|cndfs|lndfs|endfs|endfs|renault|ufscc|ndfs>"},`, which is to long to display. To me this sounds like a bug in libpopt. Which is not resolved in a the latest version.
I do not know a minimal working example to reproduce the bug, so I have not submitted bug report.

**Comment by alaarman** [comment]
@michaelw debugged this once to a bug in popt.

**Comment by Meijuh** [comment]
I am closing this issue then, not going to debug popt ;).
