### ISSUE TITLE
file name taken as --por argument: pnml2lts-mc --por problem101.pnml

### ISSUE THREAD

**Issue by jacopol** [utwente-fmt/ltsmin#134]
pnml2lts-mc --threads=64 --por problem101.pnml
pnml2lts-mc, ** error **: unknown POR algorithm problem101.pnml

--por in this case takes no argument, so problem101.pnml should be interpreted as file name.
LTSmin treated this like I typed:
pnml2lts-mc --threads=64 --por=problem101.pnml

(I did this on caserta)

**Comment by Meijuh** [comment]
After searching the interwebs for some time, I could not find a way to resolve this with popt. Maybe it is not  even possible to resolve, who knows.

**Comment by alaarman** [comment]
force thta popt demands an equals sign between parameters?
otherwise we just change the options and add --por-alg or so

**Comment by Meijuh** [comment]
Can we force popt to require `=`? Else I don't think we should put anymore effort into this issue.

**Comment by alaarman** [comment]
won't fix with popt
