### ISSUE TITLE
Compilation error on Debian Testing

### ISSUE THREAD

**Issue by johanmazel** [utwente-fmt/ltsmin#170]
I get this error message when I try to compile on Debian Testing:
libtool: compile:  clang -DHAVE_CONFIG_H -I. -I../../src/hre -I../../src -I../../src -isystem /usr/include/mit-krb5 -I/usr/include/pgm-5.2 -I/usr/include/uuid -g -O2 -W -Wall -pipe -MT libprob_la-prob_client.lo -MD -MP -MF .deps/libprob_la-prob_client.Tpo -c prob_client.c -o libprob_la-prob_client.o
prob_client.c:18:5: error: unknown type name 'zctx_t'
    zctx_t* ctx;

clang version is 7.0.1-8.
The czmq version is 4.2.0-2.

On this [thread](https://stackoverflow.com/questions/42311564/zeromq-error-unknown-type-name-zctx-t), someone links to this [release note](https://github.com/zeromq/czmq/releases/tag/v4.0.0) of czmq 4.0.0 that states that "The following classes are gone: [...] zctx [...].".
I suspect that this error is linked to this [issue](https://github.com/utwente-fmt/ltsmin/issues/149).

**Comment by Meijuh** [comment]
CZMQ version 4 is not supported by LTSmin, I think you should use version 3.
This automated check is missing and should be added to configure.

**Comment by johanmazel** [comment]
Thank you for your help.
