### ISSUE TITLE
Installing on Cygwin

### ISSUE THREAD

**Issue by matifch** [utwente-fmt/ltsmin#172]
My Current operating system is ``CYGWIN_NT-10.0 3.0.7(0.338/5/3)''
I downloaded ltsmin-v3.0.2-linux.tgz 
$ tar xvzf ltsmin-v3.0.2-linux.tgz
$ cd v3.0.2/
$ ./configure --disable-dependency-tracking --prefix /path/
-bash: ./configure: No such file or directory

-------- I am working on the following instructions given on LTSmin's website ------
\# Unpack the tarball
$ tar xvzf ltsmin-\<version\>.tar.gz
$ cd ltsmin-<version>

\# Configure
$ ./configure --disable-dependency-tracking --prefix /path/

**Comment by Meijuh** [comment]
The archive you have downloaded only contains the precompiled linux binaries. If you want to compile on Cygwin yourself you should download the archive with the sources.
However, if you do not mind running a beta version (3.1.0) of LTSmin, you can also download precompiled Windows binaries, that do not require Cygwin. You can find those binaries here: http://jmeijer.nl/ltsmin/.
