### ISSUE TITLE
Version 3.1 windows support, time to test and performance

### ISSUE THREAD

**Issue by trolando** [utwente-fmt/ltsmin#189]
I made a new 3.1 branch with work of @Meijuh 

Please @alaarman can you test if it works under Linux + Windows and if the performance is stable, the RNG of the load balancer in the -mc tools has been changed for Windows compatibility.

We also need to fix the Travis build so it works.

**Comment by alaarman** [comment]
where is it?

**Comment by trolando** [comment]
https://github.com/utwente-fmt/ltsmin/tree/3.1

**Comment by alaarman** [comment]
all works fine
