### ISSUE TITLE
FSM format direct-write check missing

### ISSUE THREAD

**Issue by Meijuh** [utwente-fmt/ltsmin#26]
lps2lts-seq --strategy=bfs ieee-11073.lps model.fsm
lps2lts-seq: mCRL2 language module initialized^M
lps2lts-seq: loading model from /home/fmg/laarman/ltsmin-hre/testsuite/../examples/ieee-11073.lps^M
lps2lts-seq: mCRL2 rewriter: jittyc^M
lps2lts-seq: length is 15, there are 290 groups^M
lps2lts-seq: There are 0 state labels and 1 edge labels^M
lps2lts-seq: got initial state^M
lps2lts-seq: Writing output to model.fsm^M
lps2lts-seq: keeping action_labels^M
segmentation fault ***^M
^M
Please send information on how to reproduce this problem to: ^M
ltsmin-support@cs.utwente.nl^M
along with all output preceding this message.^M
In addition, include the following information:^M
Package: ltsmin 1.8^M
Stack trace:^M
0: /home/fmg/laarman/ltsmin-hre/testsuite/../src/pins2lts-seq/lps2lts-seq(HREprintStack+0x18) [0x4877d8]^M
1: /home/fmg/laarman/ltsmin-hre/testsuite/../src/pins2lts-seq/lps2lts-seq [0x487e26]^M
2: /lib64/libpthread.so.0 [0x2ad690163c00]^M
FAIL: test11_fsm: Program exited with LTSMIN_EXIT_ERROR

**Comment by sccblom** [comment]
That's a bug. The tool should print something like
FSM format cannot be used because it does not allow
writing in arbitrary order.

**Comment by sccblom** [comment]
Added fix to sccblom/ltsmin

**Comment by sccblom** [comment]
The seg fault is fixed, but someone will have to review the LTS IO code
to see if the same error can occur during reading...
