### ISSUE TITLE
barrier is not cleaned up correctly

### ISSUE THREAD

**Issue by Meijuh** [utwente-fmt/ltsmin#31]
For correct barrier deallocation see http://locklessinc.com/articles/barriers/

~/ltsmin-hre/src/pins2lts-mc/dve2lts-mc ~/tests/dve/ltl-new/elevator2.3.prop4.dve2C --threads=48 --state=cleary-tree
dve2lts-mc: Precompiled divine module initialized
dve2lts-mc( 0/48), \* error _: Cleary tree not supported in combination with error trails or the MCNDFS algorithms.
segmentation fault *_*
Please send information on how to reproduce this problem to: 
ltsmin-support@cs.utwente.nl
along with all output preceding this message.
In addition, include the following information:
Package: ltsmin 1.8
Stack trace:
segmentation fault ***
Please send information on how to reproduce this problem to: 
ltsmin-support@cs.utwente.nl
along with all output preceding this message.
In addition, include the following information:
Package: ltsmin 1.8
Stack trace:

**Comment by sccblom** [comment]
-mc is Alfons responsibility not mine.

**Comment by alaarman** [comment]
Resolved
