### ISSUE TITLE
ltsmin-mpi lacking documentation on segements?

### ISSUE THREAD

**Issue by Meijuh** [utwente-fmt/ltsmin#39]
When generating a gcf file with the following command (see issue 462 for the lps file)

lps2lts-grey -c --write-state CookingKettle_v3.min.lps CookingKettle_v3.gcf

and then invoking the attached pbs file on the cluster, the following output is generated:

ltsmin-mpi( 0/10), ** error **: Number of segments 1 does not equal number of workers 10

I'm guessing that the gcf file should also have been generated by the mpi tools to get multiple segments, but this does not seem to be documented.

Stefan:
All state space generators running with N workers produce an LTS with N segments.

The MPI reduction tools require an LTS with as many segments as there are workers.

The sequential tools (especially ltstrans) can load and store an LTS with an
arbitrary number of segments.

**Comment by sccblom** [comment]
The -grey series has been discontinued. Please reopen this problem is shared by other tools.
