### ISSUE TITLE
Obtaining label information in the symbolic tools

### ISSUE THREAD

**Issue by Meijuh** [utwente-fmt/ltsmin#42]
Aim: We want to establish if a transition with a certain label is possible in our state space.

In discussion with Jaco I came up with some (symbolic) algorithms for the above and it seems that to start we need to extra pieces of functionality added two the pins interface to achieve this:

Given a label l, return the groups that potentially have a transition labeled l. I assume this should actually be split up in two functions, namely (1) given a textual label return the related number assigned to it and (2) given the number return the groups. Note that this is an over approximation: the the transition from the group might not necessarily be possible in our state space.
Given a group and a set of states (projected down to that group), is a transition labeled l possible from these states.
Once we have the above it will become possible to implement the first of the algorithms we designed. For the other two related ones some more functionality is needed:

Backward expansion of groups, i.e. given some target states I want to expand my transition relation for the group (note that if some of the data is potentially infinite this might be impossible).
Given a label l I'd like to obtain all the states from which a transition labeled l is possible.
Given a transition system, I'd like to know an upper bound for the maximum value that can be assigned to each entry of the state vector (this is needed to initialize the a bdd in atermdd to e.g. the full relation).

-----
Alfons:
see also the new --invariant violation detection, which has not yet been implemtented for the symbolic tools.

See also the EVAR variable that is defined in the mu-calculus language, but unused.

**Comment by Meijuh** [comment]
It seems this is already implemented with:

`extern int GBtransitionInGroup(model_t model, int* labels, int group);`

**Comment by alaarman** [comment]
invariant detection is now also supported in the symbolic tools
