### ISSUE TITLE
documentation issues

### ISSUE THREAD

**Issue by Meijuh** [utwente-fmt/ltsmin#49]
## Online documentation issues

1) I cannot find any link to the GCF page on the website. Maybe a
link can be added to the main page, or it might even be better
to provide a list of all available tools (e.g. similar to mCRL2:
http://mcrl2.org/wiki/index.php/Tool_manual_pages)

2) I couldn't find anywhere in the documentation what GCF stands for,
or what a GCF archive actually is.

3) In section 1 of the main page, "mCRL2" is misspelled as "mcrl2".

4) In the manual page for lpo-reach, the links to mcrl, mcrl22mcrl,
mcrl22lps and the ICTAC paper are incorrect.

5) The manual page of lps2lts-grey does not state what the file format
is of the output file.

6) According to the documentation, lps-reach "performs a reachability
analysis on a specification". I assume this means that it calculates
all reachable states.

7) The stats link on the bottom right of the main page is broken.

**Comment by alaarman** [comment]
LTSmin 2.0 release should have fixed some of these issues.
Sort this out.
Are other's still relevant?

**Comment by Meijuh** [comment]
If any of these issues pop up again just create a new issue.
