### ISSUE TITLE
Writing a gcf with lps2lts-mc does not terminate.

### ISSUE THREAD

**Issue by Meijuh** [utwente-fmt/ltsmin#53]
The command `src/pins2lts-mc/lps2lts-mc abp.mcrl2.lps --mcrl2=-rjitty /tmp/foo.gcf` does not terminate.

**Comment by alaarman** [comment]
fixed in release

**Comment by alaarman** [comment]
Solved in 195f51137d317ea7d6930bbd7b00e247a5d7fa57
