### ISSUE TITLE
Symbolic back-end can not cope with ~> 10^380 states

### ISSUE THREAD

**Issue by Meijuh** [utwente-fmt/ltsmin#55]
Currently, many vset implementations use a double to count the number of states. A floating point expection is triggered when trying to count more than 10^380 states.
A solution might be to use `long double`s, but this will not fit in the operations cache.

**Comment by alaarman** [comment]
I like this issue :)

**Comment by alaarman** [comment]
isn't this already solved with the bignum libraries?

**Comment by trolando** [comment]
There is "some" support for the bignum libraries. If I remember correctly, @Meijuh created some custom code for this. In Sylvan there is no native support for e.g. gmp, although very very recently I have implemented support for gmp rational numbers in MTBDDs, so perhaps I could use an MTBDD leaf and the Sylvan garbage collection framework thing for this too.

**Comment by Meijuh** [comment]
@trolando I don't think we need to use custom terminals for this. 
The problem with this issue was that LTSmin would crash when a floating point representing infinity was converted to a bignum; bignums don't support infinity. So, in essence LTSmin could cope with more than 10^380 states, but LTSmin would just represent this as infinity. The way I fixed it is 3-fold:
- I changed the vset interface to put the number of states directly in a double, instead of bignum: https://github.com/Meijuh/ltsmin/commit/cc2dfdda9e3ac1a097bf4b199ed9881c353df632
- The above commit also adds an extra vset function to count precisely with bignums (vset_count_precise)
- I added a vset_ccount function with can count using long doubles. Of which implementations of the vset interface use two cache entries to store the 128 bit result. The commit is here: https://github.com/Meijuh/ltsmin/commit/78b9a6f78dc0b4e72aad9a1a6007582cda441de7.

This issue can be closed when these changes are merged in this repo.

**Comment by yanntm** [comment]
Note that storing large integers in long double leads to loss of precision, particularly if adding widely different scales together, you can get some severe drift in number of states reported with long double.
Basically getting the first 12 digits right (MCC asks for that precision) was not always possible in my experiments with long double, because the result is computed as sums and multiplications of these.

GMP is the way to go imho, it's a pretty small dependency (available basically everywhere) + it has a simple C or c++ API.

**Comment by Meijuh** [comment]
This issue is resolved by now.
The symbolic backend automatically switches to long doubles if necessary.
If you want to precisely count the number of states use the `--precise` flag. This uses the GMP library.
