### ISSUE TITLE
Problem with mapa2lts-sym

### ISSUE THREAD

**Issue by buschko** [utwente-fmt/ltsmin#60]
When I use "mapa2lts-min input.mapa output.gcf" I obtain the following output for writing:

mapa2lts-sym: writing output
mapa2lts-sym: Note: ETF format does not yet support read, write and copy.

When I now invoke "ltsmin-convert -rdwr input.gcf output.ma" I obtain the message
ltsmin-convert: loading from dft_comm.gcf
ltsmin-convert, ** error **: string overflow (25189>=1024)

When using mapa2lts-dist everything is fine!

Further, in ltsmin-convert there is a new empty line after each Markovian transition when writing to a .ma file, which is a Bug.

**Comment by buschko** [comment]
just got an explanation that the symbolic toll will create an .etf and no gcf, thus maybe a warning if someone will try to get an gcf as output.

**Comment by alaarman** [comment]
Fixed.
