### ISSUE TITLE
ltsmin integration issues

### ISSUE THREAD

**Issue by axel-habermaier** [utwente-fmt/ltsmin#65]
Hello everyone,

let me start by thanking you for your hard work on ltsmin, your tool seems to be exactly what I've been looking for. Unfortunately, there are a couple of things that make it hard for me to get started with it and to integrate it into our toolchain.

I want to integrate ltsmin as the model checking backend for our tool [S#](http://safetysharp.isse.de), which is currently under heavy development. We're using S# to model safety-critical systems in C#, translating the code to SPIN and NuSMV at the moment. However, using ltsmin would be a much, much nicer way to do the model checking, as we could simply execute the S# model (it's regular C# code after all) to compute the next state. That would allow us to use more sophisticated C# features in the models, such as LINQ and so on.

So I want to use the PINS dlopen functionality to compute the next state using our actual model. Integrating native C code and managed C# code is unproblematic and should be fast enough (at least for a first try, we can always optimize it later on). There are a couple of things that make it very hard for me to do so, however:

- The documentation is severely lacking; I've found the TACAS'15 sokoban example, but that also doesn't really explain what's going on. In particular, you never seem to explain the basic structure and architecture of ltsmin from a coding point of view anywhere.
- ltsmin is heavily platform-dependent; you're using POSIX functions all over the place (at least that's what it seems like) as well as GCC-specific compiler extensions. That makes it impossible to compile ltsmin on Windows with Visual Studio, forcing me to resort to cygwin, which is suboptimal as it significantly increases the build complexity. Are there any plans to make ltsmin platform-independent (after all, there is no real reason why it should be tied to Linux)? Is there some sort of platform abstraction layer already? The ``hre`` folders maybe?
- Is there a way that I can compile ltsmin as a DLL instead of an EXE? In particular, I want to use pins2lts-sym.exe and pins2lts-mc.exe from our tool and having it available as a DLL that I can pinvoke to from C# is much nicer than calling it via the command line.

Thanks for your help
Axel

**Comment by alaarman** [comment]
Thanks for the feedback Axel.

A detailed manual on writing PINS modules is indeed due.
As for platform support, LTSmin supports OSX and Linux and assumes indeed a gcc compiler and an x86 hardware. I have ported it to Cygwin once, and this is semi-supported. Now that Cygwin 64 is finally out, we can move to support it more officially (perhaps include the cygwin dll @Meijuh ?).
Regarding the POSIX calls that are all over the place: These should indeed be moved all to the HRE library. Some parts of the tools, like the multi-core backend, already consistently do this. Others require some more effort. 
Let us know if you succeeded with your approach to use LTSmin as library. We considered this future work.
