### ISSUE TITLE
Wrong results with various VSets (including sylvan)

### ISSUE THREAD

**Issue by alaarman** [utwente-fmt/ltsmin#67]
In the next branch, the different VSet implementations give different results (ddd not tested).
When turning off copy matrices with -rr2+,w2W,W2+ the results do not change.
The problem also persists for DVE models (e.g. telephony.1). 

As reference (PROMELA model can be found in ltsmin/spins/tests/case_studies):
$ ../pins2lts-mc/prom2lts-mc ../X.509.prm.spins             
prom2lts-mc: Precompiled SpinS module initialized
prom2lts-mc( 0/ 4): Loading model from ../X.509.prm.spins
prom2lts-mc( 0/ 4): There are 136 state labels and 2 edge labels
prom2lts-mc( 0/ 4): State length is 109, there are 58 groups
prom2lts-mc( 0/ 4): Running bfs using 4 cores
prom2lts-mc( 0/ 4): Using a non-indexing tree table with 2^28 elements
prom2lts-mc( 0/ 4): Successor permutation: none
prom2lts-mc( 0/ 4): Global bits: 0, count bits: 0, local bits: 0
prom2lts-mc( 0/ 4): ~69 levels ~10000 states ~36708 transitions
prom2lts-mc( 0/ 4):  
prom2lts-mc( 0/ 4): mean standard work distribution: 11.1% (states) 13.7% (transitions)
prom2lts-mc( 0/ 4):  
prom2lts-mc( 0/ 4): Explored 9028 states 35999 transitions, fanout: 3.987

$ ./prom2lts-sym ../X.509.prm.spins --vset=ldd64
Initializing Lace, 4 workers.
Lace startup, creating 4 worker threads with program stack 524288 bytes.
prom2lts-sym: Exploration order is bfs-prev
prom2lts-sym: Saturation strategy is none
prom2lts-sym: Guided search strategy is unguided
prom2lts-sym: Attractor strategy is default
prom2lts-sym: Precompiled SpinS module initialized
prom2lts-sym: opening ../X.509.prm.spins
prom2lts-sym: state vector length is 109; there are 58 groups and 123 guards
prom2lts-sym: Creating a native ListDD 64-bit domain.
prom2lts-sym: initial node table has 832040 entries
prom2lts-sym: initial uniq table has 1346269 entries
prom2lts-sym: initial op cache has 1346269 entries
prom2lts-sym: initial stack size 17711
prom2lts-sym: Using GBgetTransitionsShort as next-state function
prom2lts-sym: got initial state
prom2lts-sym: level 0 is finished
prom2lts-sym: vrel_add_act not supported; falling back to vrel_add_cpy.
...
prom2lts-sym: Exploration took 3132 group checks and 3132 next state calls
prom2lts-sym: reachability took 0.510 real 0.450 user 0.020 sys
prom2lts-sym: counting visited states...
prom2lts-sym: counting took 0.000 real 0.000 user 0.000 sys
prom2lts-sym: state space has 9028 (~9.03e+03) states, 5222 BDD nodes

$ ./prom2lts-sym ../X.509.prm.spins --vset=ldd  
Initializing Lace, 4 workers.
Lace startup, creating 4 worker threads with program stack 524288 bytes.
prom2lts-sym: Exploration order is bfs-prev
prom2lts-sym: Saturation strategy is none
prom2lts-sym: Guided search strategy is unguided
prom2lts-sym: Attractor strategy is default
prom2lts-sym: Precompiled SpinS module initialized
prom2lts-sym: opening ../X.509.prm.spins
prom2lts-sym: state vector length is 109; there are 58 groups and 123 guards
prom2lts-sym: Creating a native ListDD domain.
prom2lts-sym: initial node table has 832040 entries
prom2lts-sym: initial uniq table has 1346269 entries
prom2lts-sym: initial op cache has 1346269 entries
prom2lts-sym: initial stack size 17711
prom2lts-sym: Using GBgetTransitionsShort as next-state function
prom2lts-sym: got initial state
prom2lts-sym: level 0 is finished
prom2lts-sym: Exploration took 58 group checks and 58 next state calls
prom2lts-sym: reachability took 0.010 real 0.000 user 0.000 sys
prom2lts-sym: counting visited states...
prom2lts-sym: counting took 0.000 real 0.000 user 0.000 sys
prom2lts-sym: state space has 1 (~1.00e+00) states, 111 BDD nodes

$ ./prom2lts-sym ../X.509.prm.spins --vset=list                          
Initializing Lace, 4 workers.
Lace startup, creating 4 worker threads with program stack 524288 bytes.
prom2lts-sym: Exploration order is bfs-prev
prom2lts-sym: Saturation strategy is none
prom2lts-sym: Guided search strategy is unguided
prom2lts-sym: Attractor strategy is default
prom2lts-sym: Precompiled SpinS module initialized
prom2lts-sym: opening ../X.509.prm.spins
prom2lts-sym: state vector length is 109; there are 58 groups and 123 guards
prom2lts-sym: Creating an AtermDD list domain.
prom2lts-sym: Using GBgetTransitionsShort as next-state function
prom2lts-sym: got initial state
prom2lts-sym: level 0 is finished
prom2lts-sym: Exploration took 58 group checks and 58 next state calls
prom2lts-sym: reachability took 0.000 real 0.000 user 0.000 sys
prom2lts-sym: counting visited states...
prom2lts-sym: counting took 0.000 real 0.000 user 0.000 sys
prom2lts-sym: state space has 1 (~1.00e+00) states, 111 BDD nodes

$ ./prom2lts-sym ../X.509.prm.spins --vset=tree
Initializing Lace, 4 workers.
Lace startup, creating 4 worker threads with program stack 524288 bytes.
prom2lts-sym: Exploration order is bfs-prev
prom2lts-sym: Saturation strategy is none
prom2lts-sym: Guided search strategy is unguided
prom2lts-sym: Attractor strategy is default
prom2lts-sym: Precompiled SpinS module initialized
prom2lts-sym: opening ../X.509.prm.spins
prom2lts-sym: state vector length is 109; there are 58 groups and 123 guards
prom2lts-sym: Creating an AtermDD tree domain.
prom2lts-sym: Using GBgetTransitionsShort as next-state function
prom2lts-sym: got initial state
prom2lts-sym: level 0 is finished
prom2lts-sym: Exploration took 58 group checks and 58 next state calls
prom2lts-sym: reachability took 0.010 real 0.000 user 0.000 sys
prom2lts-sym: counting visited states...
prom2lts-sym: counting took 0.000 real 0.000 user 0.000 sys
prom2lts-sym: state space has 1 (~1.00e+00) states, 268 BDD nodes

$ ./prom2lts-sym ../X.509.prm.spins --vset=fdd                 
Initializing Lace, 4 workers.
Lace startup, creating 4 worker threads with program stack 524288 bytes.
prom2lts-sym: Exploration order is bfs-prev
prom2lts-sym: Saturation strategy is none
prom2lts-sym: Guided search strategy is unguided
prom2lts-sym: Attractor strategy is default
prom2lts-sym: Precompiled SpinS module initialized
prom2lts-sym: opening ../X.509.prm.spins
prom2lts-sym: state vector length is 109; there are 58 groups and 123 guards
prom2lts-sym: Creating a BuDDy fdd domain.
prom2lts-sym: Buddy dynamic reordering strategy: none
prom2lts-sym: ratio 64, maximum increase 1000000, minimum free 20
prom2lts-sym: Using GBgetTransitionsShort as next-state function
prom2lts-sym: got initial state
prom2lts-sym: level 0 is finished
prom2lts-sym: Exploration took 58 group checks and 58 next state calls
prom2lts-sym: reachability took 0.030 real 0.020 user 0.000 sys
prom2lts-sym: counting visited states...
prom2lts-sym: counting took 0.000 real 0.000 user 0.000 sys
prom2lts-sym: state space has 1 (~1.00e+00) states, 1744 BDD nodes

$ ./prom2lts-sym ../X.509.prm.spins --vset=sylvan
Initializing Lace, 4 workers.
Lace startup, creating 4 worker threads with program stack 524288 bytes.
prom2lts-sym: Exploration order is bfs-prev
prom2lts-sym: Saturation strategy is none
prom2lts-sym: Guided search strategy is unguided
prom2lts-sym: Attractor strategy is default
prom2lts-sym: Precompiled SpinS module initialized
prom2lts-sym: opening ../X.509.prm.spins
prom2lts-sym: state vector length is 109; there are 58 groups and 123 guards
prom2lts-sym: Creating a Sylvan domain.
prom2lts-sym: Using GBgetTransitionsShort as next-state function
prom2lts-sym: got initial state
.....
prom2lts-sym: Exploration took 2784 group checks and 2784 next state calls
prom2lts-sym: reachability took 7.410 real 26.890 user 0.340 sys
prom2lts-sym: counting visited states...
prom2lts-sym: counting took 0.020 real 0.050 user 0.000 sys
prom2lts-sym: state space has 10543 (~1.05e+04) states, 70572 BDD nodes

$ ./prom2lts-sym ../X.509.prm.spins --vset=lddmc 
Initializing Lace, 4 workers.
Lace startup, creating 4 worker threads with program stack 524288 bytes.
prom2lts-sym: Exploration order is bfs-prev
prom2lts-sym: Saturation strategy is none
prom2lts-sym: Guided search strategy is unguided
prom2lts-sym: Attractor strategy is default
prom2lts-sym: Precompiled SpinS module initialized
prom2lts-sym: opening ../X.509.prm.spins
prom2lts-sym: state vector length is 109; there are 58 groups and 123 guards
prom2lts-sym: Creating a multi-core ListDD domain.
prom2lts-sym: Using GBgetTransitionsShort as next-state function
prom2lts-sym: got initial state
prom2lts-sym: level 0 is finished
prom2lts-sym: vrel_add_act not supported; falling back to vrel_add_cpy
.....
prom2lts-sym: Exploration took 3132 group checks and 3132 next state calls
prom2lts-sym: reachability took 2.220 real 5.980 user 0.540 sys
prom2lts-sym: counting visited states...
prom2lts-sym: counting took 0.000 real 0.010 user 0.000 sys
prom2lts-sym: state space has 9028 (~9.03e+03) states, 5220 BDD nodes

**Comment by trolando** [comment]
Well at least the lddmc version seems to work fine.

Maybe @Meijuh can do a nice bisect of the code? I am not really available for 2.5 weeks.

**Comment by alaarman** [comment]
Are those other vsets also BDDs (not MDDs)? It could be the fdd-bits setting. But in the case of telephony.1, I doubt that this is the problem (it does not seem to have large or negative integers).

In any case, I am kind of surprised that this wasn't caught by the testsuite.

**Comment by alaarman** [comment]
@Meijuh cannot reproduce this on Debian.
@trolando Can you reproduce it on your mac (I'm on El Capitan btw). See inputs in #66 .

Sylvan seems to work now for the examples above, see 9e66acbcbb920fc6bbd3b4a6c837d39a4c9b4f47, 7d4373b1278819be44e26777580f63ff0037ffc3 and https://github.com/utwente-fmt/divine2/pull/1

**Comment by alaarman** [comment]
Fixed in next.
Also: 9f8386e08dfefaa5ead5a0dc5f436d8e0cef8588
