### ISSUE TITLE
git submodule update

### ISSUE THREAD

**Issue by buschko** [utwente-fmt/ltsmin#7]
I obtain the following messages for a submodule update (I'm currently using the next brach of ltsmin)

fatal: reference is not a tree: a443e1a236163463a703cc81f2e614c5a68ff765
fatal: reference is not a tree: ae6fdce1a8dcf3a5f6d8f6f58bc73e4efcda702a
Unable to checkout 'a443e1a236163463a703cc81f2e614c5a68ff765' in submodule path 'buddy'
Unable to checkout 'ae6fdce1a8dcf3a5f6d8f6f58bc73e4efcda702a' in submodule path 'sylvan'

**Comment by trolando** [comment]
Please use "git submodule sync" and retry.

**Comment by buschko** [comment]
thx, this helped :)
