### ISSUE TITLE
[Performance] Optimize state label callback

### ISSUE THREAD

**Issue by axel-habermaier** [utwente-fmt/ltsmin#73]
The state label call back currently has the following signature:

``` C
int32_t StateLabelCallback(model_t model, int32_t label, int32_t* state)
```

Consequently, for a model with `n` state labels, the callback is called `n` times per state (at least that is what it seems like -- we're not using transition groups at the moment). The problem is that the models that our tool checks with LtsMin do not natively understand the state vector, hence the state vector has to be deserialized into a structure that our models actually understand. We've spend significant effort in making the state serialization and deserialization as fast and efficient as possible with great success; so far, serialization overhead over an entire model checking run is below 10% of the entire model checking time.

It might help, however, if the signature of the state label callback would be changed to the following:

``` C
int32_t* StateLabelCallback(model_t model, int32_t label*, int32_t labelCount, int32_t* state)
```

The semantics being that `label` is an array of labels of size `labelCount` that contains all labels that should be checked for `state`. The result would be returned as an `int32_t` array of the same size as `label` in the same order as `label`. That would improve performance in two ways:
1. The callback would only have to be called once per state, not `labelCount` times often per state, reducing the overhead of the indirect function call (admittedly, a minor improvement). 
2. For models such as ours, however, the bigger consequence would be that we would only have to deserialize the `state` once for all labels, reducing the serialization overhead noticeably for complex formulas which require many state labels.

I don't know if this optimization would be incompatible with transition groups or other advanced features that we currently do not use. Of course, the more expensive state deserialization is, the more useful this optimization becomes. So while it's currently not a significant pain point for us, it is still - at least as far as I can see - a somewhat unfortunate design decision.

**Comment by Meijuh** [comment]
I think this: https://github.com/utwente-fmt/ltsmin/blob/master/src/pins-lib/pins.h#L401 is actually the function you are looking for. As for the possible incompatibility with transition groups or other features -- this is not an issue, state label evaluation is an independent feature in LTSmin. Let me know if the function is what you need. The argument `int*labels` is where you need to store the result of the state labels. Where the index is the state label number. The language front-end should know all/the-number-of state labels.

**Comment by Meijuh** [comment]
Also I must add that it depends on the back-end if it supports the function. I don't think the symbolic back-end does, but multi-core explicit back-end does.

**Comment by axel-habermaier** [comment]
Thanks for the hint - but how am I supposed to use this function? When initializing the model, I removed the call to ``GBsetStateLabelLong(model, StateLabelCallbackOld);`` and replaced it with ``GBsetStateLabelsAll(model, StateLabelCallback);``; now LtsMin crashes when calling ``GBsetStateLabelInfo(model, &StateLabelMatrix);`` (no error message or stack trace is provided, which is probably a cygwin issue). Removing the call to ``GBsetStateLabelInfo`` results in a segmentation fault.

Also, I noticed that there is a ``GBsetNextStateAll`` function. Does that have any benefits over ``GBsetNextStateLong``?

**Comment by alaarman** [comment]
It depends on your language frontend. Sometimes it can be fater to generate all successors at once for a state (or obtain all labels at once). It could avoid redundant deserializations and reuse successor computation results.
But it also depends on the tool you use. The multi-core tool benefits from the *All functions, as it queries complete states and uses the dependency matrix only to decompose states later in the tree storage or in the POR layer. The symbolic tool however exclusively queries individual groups from the model, projecting states to short states immediately using the *Short functions (In fact, it only stores the short states in the transition relations.)

The way pins.c works is by providing default *Short, *Long, and *All implementations (this code should be pretty readable). If one of these is overwritten, the other two default implementations use it.
Ill have a look at the code to see if something is wrong for these default state label implementations. You could next time try to use gdb to generate an error trace (I usually set a breakpoint on HREprintStack or HREabort).

**Comment by alaarman** [comment]
So if one want the best performance across tools, one should implement all functions (*All, *Short and *Long). Unless of course the language frontend does not allow for any optimization in one of these functions. The Promela frontend (SpinS), for example, implements *All and *Long, as the former avoids repeated guard evaluations. It would however not benefit from a direct *Short implementation as it does not require serialization / deserialization of states (successor computation uses the LTSmin state vector directly).

**Comment by Meijuh** [comment]
Closing this issue, since it has been long inactive.
