### ISSUE TITLE
Spins compilation issue

### ISSUE THREAD

**Issue by Meijuh** [utwente-fmt/ltsmin#75]
While compiling LTSmin without a Java JDK, make reports:

test -f spins/spins.jar || (cd "./spins/src" && /usr/local/bin/ant)
Unable to find any JVMs matching version "(null)".
No Java runtime present, try --request to install.
No Java runtime present, requesting install.
make[1]: **\* [spins/spins.jar] Error 1
make: **\* [all-recursive] Error 1

**Comment by alaarman** [comment]
CHECK_JDK was disabled in m4/acx_spins.m4 as it does not find OpenJDK
Maybe replace with a check for the presence of "javac" command?
