### ISSUE TITLE
Sylvan OSX

### ISSUE THREAD

**Issue by alaarman** [utwente-fmt/ltsmin#78]
To compile Sylvan on OSX, my system requires that I pass the following to make:
CXXFLAGS="-lhwloc"

**Comment by alaarman** [comment]
/opt/local/lib/libhwloc.dylib

**Comment by Meijuh** [comment]
Is this on your DYLD_LIBRARY_PATH? if I install hwloc with brew it ends up in here: 

    locate libhwloc.dylib
    /usr/local/Cellar/hwloc/1.11.0/lib/libhwloc.dylib
    /usr/local/Cellar/hwloc/1.11.2/lib/libhwloc.dylib
    /usr/local/lib/libhwloc.dylib

And I do not have to add -lhwloc.

**Comment by alaarman** [comment]
MacPorts uses /opt/local

$ locate libhwloc.dylib
/opt/local/lib/libhwloc.dylib

I assume that answers your question with "yes"?

**Comment by Meijuh** [comment]
I think so, I would need to look into it further then... I think this is a problem with Sylvan btw, not with LTSmin.

**Comment by trolando** [comment]
Actually HWLOC should not be necessary. Without HWLOC it should compile fine. There is a check in configure.ac that sets HAVE_LIBHWLOC to false and then Sylvan should compile without using hwloc stuff.

**Comment by trolando** [comment]
I think we should get travis support in the master branch and set it up to catch these errors if they are still there. I no longer have a Mac to test with.

**Comment by Meijuh** [comment]
But, this check should go into the Sylvan repo right?

**Comment by trolando** [comment]
Sylvan has these checks, both in the CMake files as well as in the autoconf files.

Sylvan's Makefile.am (in the src dir) already adds hwloc to the library (using libsylvan_la_LIB_ADD)
