### ISSUE TITLE
Integers no longer supported in expressions

### ISSUE THREAD

**Issue by alaarman** [utwente-fmt/ltsmin#81]
The type that SpinS gives to the referenced slot in the below expression is a "byte". The type checker now requires "numeric"

$ pins2lts-sym/prom2lts-sym X.509.prm.spins -i "TC_0.d==1"
prom2lts-sym: Exploration order is bfs-prev
prom2lts-sym: Saturation strategy is none
prom2lts-sym: Guided search strategy is unguided
prom2lts-sym: Attractor strategy is default
prom2lts-sym: Precompiled SpinS module initialized
prom2lts-sym: opening X.509.prm.spins
prom2lts-sym: state vector length is 97; there are 58 groups
prom2lts-sym, *\* error **: Expression with type "numeric" can only be used if the language front-end defines it: "1"

**Comment by Meijuh** [comment]
This issue is not valid anymore. It is resolved.

**Comment by alaarman** [comment]
This is fixed in Next?

**Comment by Meijuh** [comment]
Yes (in)equality checks are now supported due to this line: https://github.com/utwente-fmt/ltsmin/blob/next/src/ltsmin-lib/ltsmin-type-system.h#L106.
