### ISSUE TITLE
Null pointer in type checker

### ISSUE THREAD

**Issue by alaarman** [utwente-fmt/ltsmin#82]
in ltsmin-type-system.c:31 
        char hint[hint_binary(f, NULL, 0) + 1];

The NULL causes a null pointer dereference.

**Comment by Meijuh** [comment]
I don't think it does. If `NULL` is supplied as the second argument to `hint_binary`, then `hint_binary` will just compute the length of the string and not write anything to memory.
Also I can't reproduce a bug for this issue.
