### ISSUE TITLE
mu-calculus: syntax error or file not found?

### ISSUE THREAD

**Issue by jacopol** [utwente-fmt/ltsmin#88]
etf2lts-sym --mu deadlock1.mu abp.etf
etf2lts-sym, ** error **: syntax error near pos 11

The error message is slightly strange, since in this case the real error is that the file deadlock1.mu could not be found. But since the file is not found, pins2lts-sym interprets "deadlock1.mu" as a formula.

**Comment by Meijuh** [comment]
There is now an explicit notice when an option value is parsed as a formula instead of a file.
