### ISSUE TITLE
trace generation for symbolic invariant generation

### ISSUE THREAD

**Issue by jacopol** [utwente-fmt/ltsmin#89]
etf2lts-sym --invariant "s9_R!=\"OpIdNoIndex(e0_4,SortId(Enum4))\"" abp.etf --trace=inv.gcf
etf2lts-sym: Invariant violation (s9_R!="OpIdNoIndex(e0_4,SortId(Enum4))") found at depth 4!

However, the trace is not generated, and the --trace flag is silently ignored.

**Comment by Meijuh** [comment]
This is implemented now.
